In [4]:
#task1 Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays

import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) # create first array
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]) #create second array

print("Common values between two arrays:")
print(np.intersect1d(a, b))

Common values between two arrays:
[2 4]


In [67]:
#task 2 - Create  5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you
#do not need to explicitly key in every integer value.

array = np.arange(1,16).reshape(3,5).T  # start array from 1 to 16 not including 16. reshape it to 3*5 and swap Axes
array


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [68]:
#task 3 - remove from array a any items that are also present in array b
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])


np.setdiff1d(a, b) # this function returns sorted array of elements in a that do not appear in b
  


array([ 1,  7,  8, 15])

In [69]:
#task 4:
#Total distance NYC-Key West- 1443 miles
#Strategy - I created a list in which I will record the daily value that the odometer shows
# Index [0] = 55 -> miles on day 1, index 1 shows I drove cumulative 120 miles
# day 4

miles_day=[55,120,160,160,180,190,200,300,350,350,398,440,460,520,560,580,600,800,800,898,950,
           1000,1020,1050,1090,1150,1150,1200,1250,1300,1350,1380,1399,1420,1443]

# I created a numpy array instead of a list
miles_day_numpy=np.array(miles_day)
print(miles_day_numpy)


[  55  120  160  160  180  190  200  300  350  350  398  440  460  520  560
  580  600  800  800  898  950 1000 1020 1050 1090 1150 1150 1200 1250 1300
 1350 1380 1399 1420 1443]


In [70]:
total_days=miles_day_numpy.shape[0] # this will print trip duration. The shape function was used to get length of numpy array
print("Total days: ",total_days)


Total days:  35


In [71]:
#display how many miles we drove each day
#I used Numpy ediff1d- this function takes difference between each consecutive day
firstday=miles_day_numpy[0]
miles_each_day=np.ediff1d(miles_day_numpy,to_begin=firstday)
print(miles_each_day)

[ 55  65  40   0  20  10  10 100  50   0  48  42  20  60  40  20  20 200
   0  98  52  50  20  30  40  60   0  50  50  50  50  30  19  21  23]


In [72]:
# display all rest days - 4 off days
miles_each_day[miles_each_day==0]

array([0, 0, 0, 0])

In [73]:
#display the total miles using sum array function
total_driven=miles_each_day.sum()
print("Total driven: ",total_driven)

Total driven:  1443


In [75]:
#Printing avg miles drove each day using m ean function
avg=miles_each_day.mean()
print("average driven daily: ",avg)

average driven daily:  41.2285714286


In [78]:
# task 5
import pandas as pd
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pd.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

print(nyc_water)

[[    1979.   7102100.      1512.       213. ]
 [    1980.   7071639.      1506.       213. ]
 [    1981.   7089241.      1309.       185. ]
 [    1982.   7109105.      1382.       194. ]
 [    1983.   7181224.      1424.       198. ]
 [    1984.   7234514.      1465.       203. ]
 [    1985.   7274054.      1326.       182. ]
 [    1986.   7319246.      1351.       185. ]
 [    1987.   7342476.      1447.       197. ]
 [    1988.   7353719.      1484.       202. ]
 [    1989.   7344175.      1402.       191. ]
 [    1990.   7335650.      1424.       194. ]
 [    1991.   7374501.      1469.       199. ]
 [    1992.   7428944.      1369.       184. ]
 [    1993.   7506166.      1368.5      182. ]
 [    1994.   7570458.      1357.7      179. ]
 [    1995.   7633040.      1325.7      174. ]
 [    1996.   7697812.      1297.9      169. ]
 [    1997.   7773443.      1205.5      155. ]
 [    1998.   7858259.      1219.5      155. ]
 [    1999.   7947660.      1237.2      156. ]
 [    2000.  

In [105]:
#5.1 What is the maximum yearly NYC consumption of water in millions of gallons per day?
max_yearly_cons = np.max(nyc_water[:,2], axis=0)
print(max_yearly_cons)


1512.0


In [107]:
#5.2 How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
number_of_years = nyc_water.shape[0]
print("Number of calendar years",number_of_years)

Number of calendar years 39


In [96]:
#5.3 What is the mean and the standard deviation of the per capita daily water consumption?
mean = np.mean(nyc_water[:,3], axis=0)
std = np.std(nyc_water[:,3], axis=0)
print("Mean value of the per capita daily water consumption ",mean)
print("stdv value of the per capita daily water consumption ",std)

Mean value of the per capita daily water consumption  160.307692308
stdv value of the per capita daily water consumption  31.5189433037


In [103]:
#5.4 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
# of differences and save that to a variable called "pop_diff", then print that variable to the screen.
#all negative values will describe a decrease in population
pop_diff = np.diff(nyc_water[:,1])

print(pop_diff)

[ -30461.    17602.    19864.    72119.    53290.    39540.    45192.
   23230.    11243.    -9544.    -8525.    38851.    54443.    77222.
   64292.    62582.    64772.    75631.    84816.    89401.    60618.
   16685.5   16685.5   16685.5   16685.5   16685.5   16685.5   16685.5
   16685.5   16685.5   16685.5  108965.    77081.    61281.    49530.
   44512.    21171.    85025. ]
